# Generated by Django 6.0 on 2026-01-15 18:50

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Oquv yili',
                'db_table': 'academic_years',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Kafedralar',
                'db_table': 'Kafedralar',
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('max_file_size_mb', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('allowed_extensions', models.JSONField(default=list)),
                ('approval_workflow', models.JSONField()),
                ('deadline_hours', models.IntegerField(default=48)),
                ('requires_subject', models.BooleanField(default=False, help_text="Agar rost bo'lsa, hujjat yuklashda fan tanlash majburiy bo'ladi")),
                ('requires_academic_year', models.BooleanField(default=False, help_text="Agar rost bo'lsa, hujjat yuklashda o'quv yili tanlash majburiy bo'ladi")),
                ('requires_group', models.BooleanField(default=False, help_text="Agar rost bo'lsa, hujjat yuklashda guruh tanlash majburiy bo'ladi")),
                ('allowed_roles', models.JSONField(blank=True, default=list, help_text="Bu turdagi hujjat yuklashi mumkin bo'lgan rollar ro'yxati. Bo'sh bo'lsa, hamma yuklashi mumkin.")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Hujjat turlari',
                'db_table': 'document_types',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Fakultetlar',
                'db_table': 'fakultetlar',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Guruhlar',
                'db_table': 'groups',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('address', models.TextField()),
                ('website', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Universities',
                'db_table': 'universitetlar',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('middle_name', models.CharField(blank=True, max_length=150)),
                ('roles_data', models.JSONField(blank=True, default=list, help_text='Foydalanuvchi rollari JSON formatda', verbose_name='Rollar')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('hemis_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.department')),
                ('managed_department', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head', to='documents.department')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.faculty')),
                ('managed_faculty', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dean', to='documents.faculty')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.group')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='uploaded', max_length=20)),
                ('current_step', models.IntegerField(default=0)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('verification_code', models.CharField(editable=False, max_length=4, unique=True)),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('final_pdf', models.FileField(blank=True, null=True, upload_to='approved_documents/')),
                ('title', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.academicyear')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.documenttype')),
                ('related_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.group')),
            ],
            options={
                'verbose_name_plural': 'Hujjatlar',
                'db_table': 'documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.IntegerField()),
                ('role_required', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('auto_approved', 'Auto-Approved'), ('rejected', 'Rejected'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('deadline', models.DateTimeField()),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_tasks', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to='documents.document')),
            ],
            options={
                'verbose_name_plural': 'Tasdiqlash bosqichlari',
                'db_table': 'approval_steps',
                'ordering': ['step_order'],
                'unique_together': {('document', 'step_order')},
            },
        ),
        migrations.CreateModel(
            name='ApprovalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('auto_approved', 'Auto-Approved')], max_length=20)),
                ('comment', models.TextField(blank=True, validators=[django.core.validators.MinLengthValidator(20)])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_actions', to=settings.AUTH_USER_MODEL)),
                ('approval_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='documents.approvalstep')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_logs', to='documents.document')),
            ],
            options={
                'verbose_name_plural': 'Tasdiqlash loglari',
                'db_table': 'approval_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='documents.faculty'),
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Yo'nalish nomi")),
                ('code', models.CharField(max_length=20, unique=True, verbose_name="Yo'nalish kodi")),
                ('degree_level', models.CharField(choices=[('bachelor', 'bakalavr'), ('master', 'magistr'), ('phd', 'PhD')], default='bakalavr', max_length=50)),
                ('duration_years', models.IntegerField(default=4, verbose_name="O'qish muddati (yil)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='documents.department')),
            ],
            options={
                'verbose_name': "Yo'nalish",
                'verbose_name_plural': "Yo'nalishlar",
                'db_table': 'programs',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='documents.program'),
        ),
        migrations.AddField(
            model_name='user',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.program'),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(choices=[('student', 'Talaba'), ('teacher', "O'qituvchi"), ('department_head', 'Kafedra mudiri'), ('faculty_dean', 'Fakultet dekani'), ('dean_deputy', "Dekan o'rinbosari"), ('academic_office', "O'quv bo'limi"), ('registration_office', 'Registratura'), ('director', 'Direktor'), ('director_deputy', "Direktor o'rinbosari")], help_text='Bu rol qaysi asosiy tizim roliga mos keladi', max_length=30, verbose_name='Rol tipi')),
                ('name', models.CharField(max_length=100, verbose_name='Rol nomi')),
                ('code', models.CharField(help_text='Ichki identifikator (masalan: SENIOR_TEACHER)', max_length=50, unique=True, verbose_name='Rol kodi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('is_default', models.BooleanField(default=False, verbose_name='Standart rol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Rollar',
                'db_table': 'roles',
                'ordering': ['role_type', 'name'],
                'indexes': [models.Index(fields=['role_type', 'is_active'], name='roles_role_ty_00f0e1_idx'), models.Index(fields=['code'], name='roles_code_25c050_idx')],
                'unique_together': {('role_type', 'code')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='active_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_users', to='documents.role'),
        ),
        migrations.AddField(
            model_name='user',
            name='primary_role',
            field=models.ForeignKey(blank=True, help_text="Asosiy ko'rsatiladigan rol", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_users', to='documents.role', verbose_name='Asosiy rol'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Fan nomi')),
                ('code', models.CharField(max_length=20, verbose_name='Fan kodi')),
                ('taught_in_programs', models.CharField(blank=True, default='TEMP', help_text="Yo'nalish kodlari vergul bilan ajratilgan. Masalan: BAA,DAA,TAA", max_length=500, verbose_name="Qaysi yo'nalishlarda o'tiladi")),
                ('credits', models.IntegerField(default=3, verbose_name='Kredit')),
                ('lecture_hours', models.IntegerField(default=30, verbose_name="Ma'ruza soatlari")),
                ('practice_hours', models.IntegerField(default=30, verbose_name='Amaliyot soatlari')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='documents.department')),
            ],
            options={
                'verbose_name': 'Fan',
                'verbose_name_plural': 'Fanlar',
                'db_table': 'subjects',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.subject'),
        ),
        migrations.CreateModel(
            name='TeachingAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(default=1, help_text='1, 2, 3...')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='documents.academicyear')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocations_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='documents.department')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_allocations', to='documents.group')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='documents.subject')),
                ('teacher', models.ForeignKey(limit_choices_to={'primary_role__role_type': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_allocations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teaching_allocations',
            },
        ),
        migrations.AddField(
            model_name='faculty',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculties', to='documents.university'),
        ),
        migrations.AddField(
            model_name='user',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.university'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('faculty', 'code')},
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('document_uploaded', 'Document Uploaded'), ('approval_needed', 'Approval Needed'), ('document_approved', 'Document Approved'), ('document_rejected', 'Document Rejected'), ('deadline_approaching', 'Deadline Approaching'), ('deadline_reminder', 'Deadline Reminder'), ('deadline_urgent', 'Deadline Urgent'), ('deadline_24h', 'Deadline 24H'), ('deadline_2h', 'Deadline 2H'), ('auto_approved', 'Auto-Approved')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_urgent', models.BooleanField(default=False)),
                ('sent_email', models.BooleanField(default=False)),
                ('sent_push', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.document')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Bildirishnomalar',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', 'created_at'], name='notificatio_recipie_06c470_idx')],
            },
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('program', 'name')},
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status', 'uploaded_by'], name='documents_status_87e09d_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_type', 'status'], name='documents_documen_f2a694_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['verification_code'], name='documents_verific_359c39_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['uuid'], name='documents_uuid_1d767f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teachingallocation',
            unique_together={('subject', 'group', 'academic_year', 'semester')},
        ),
        migrations.AlterUniqueTogether(
            name='faculty',
            unique_together={('university', 'code')},
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['primary_role', 'faculty', 'department'], name='users_primary_bc70f7_idx'),
        ),
    ]
