# Generated by Django 6.0 on 2026-01-15 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='users_primary_bc70f7_idx',
        ),
        migrations.AlterField(
            model_name='teachingallocation',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'active_role__role_type': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_allocations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='roles_data',
            field=models.TextField(blank=True, default='', help_text='Foydalanuvchi rollari kodlari vergul bilan ajratilgan', verbose_name='Rollar'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['active_role', 'faculty', 'department'], name='users_active__f525ba_idx'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='primary_role',
        ),
    ]
