# Generated by Django 6.0 on 2026-01-16 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_securitypolicy'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='requestlog',
            new_name='request_log_created_4f2782_idx',
            old_name='request_lo_created_7e6d27_idx',
        ),
        migrations.RenameIndex(
            model_name='requestlog',
            new_name='request_log_status__5a9c0b_idx',
            old_name='request_lo_status__d6f1dd_idx',
        ),
        migrations.RenameIndex(
            model_name='requestlog',
            new_name='request_log_method_9e699f_idx',
            old_name='request_lo_method_1c97a9_idx',
        ),
        migrations.RenameIndex(
            model_name='requestlog',
            new_name='request_log_path_5a9834_idx',
            old_name='request_lo_path_c1ad35_idx',
        ),
    ]
